// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/ws.proto

#include "proto/ws.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace openfoxwq {
PROTOBUF_CONSTEXPR WsLoginRequest::WsLoginRequest(
    ::_pbi::ConstantInitialized) {}
struct WsLoginRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR WsLoginRequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~WsLoginRequestDefaultTypeInternal() {}
  union {
    WsLoginRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 WsLoginRequestDefaultTypeInternal _WsLoginRequest_default_instance_;
PROTOBUF_CONSTEXPR WsLoginResponse::WsLoginResponse(
    ::_pbi::ConstantInitialized) {}
struct WsLoginResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR WsLoginResponseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~WsLoginResponseDefaultTypeInternal() {}
  union {
    WsLoginResponse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 WsLoginResponseDefaultTypeInternal _WsLoginResponse_default_instance_;
}  // namespace openfoxwq
static ::_pb::Metadata file_level_metadata_proto_2fws_2eproto[2];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_proto_2fws_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_proto_2fws_2eproto = nullptr;

const uint32_t TableStruct_proto_2fws_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::openfoxwq::WsLoginRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::openfoxwq::WsLoginResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::openfoxwq::WsLoginRequest)},
  { 6, -1, -1, sizeof(::openfoxwq::WsLoginResponse)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::openfoxwq::_WsLoginRequest_default_instance_._instance,
  &::openfoxwq::_WsLoginResponse_default_instance_._instance,
};

const char descriptor_table_protodef_proto_2fws_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\016proto/ws.proto\022\topenfoxwq\"\020\n\016WsLoginRe"
  "quest\"\021\n\017WsLoginResponseB%Z#github.com/a"
  "le64bit/openfoxwq/proto"
  ;
static ::_pbi::once_flag descriptor_table_proto_2fws_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_proto_2fws_2eproto = {
    false, false, 103, descriptor_table_protodef_proto_2fws_2eproto,
    "proto/ws.proto",
    &descriptor_table_proto_2fws_2eproto_once, nullptr, 0, 2,
    schemas, file_default_instances, TableStruct_proto_2fws_2eproto::offsets,
    file_level_metadata_proto_2fws_2eproto, file_level_enum_descriptors_proto_2fws_2eproto,
    file_level_service_descriptors_proto_2fws_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_proto_2fws_2eproto_getter() {
  return &descriptor_table_proto_2fws_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_proto_2fws_2eproto(&descriptor_table_proto_2fws_2eproto);
namespace openfoxwq {

// ===================================================================

class WsLoginRequest::_Internal {
 public:
};

WsLoginRequest::WsLoginRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase(arena, is_message_owned) {
  // @@protoc_insertion_point(arena_constructor:openfoxwq.WsLoginRequest)
}
WsLoginRequest::WsLoginRequest(const WsLoginRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase() {
  WsLoginRequest* const _this = this; (void)_this;
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:openfoxwq.WsLoginRequest)
}





const ::PROTOBUF_NAMESPACE_ID::Message::ClassData WsLoginRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl,
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl,
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*WsLoginRequest::GetClassData() const { return &_class_data_; }







::PROTOBUF_NAMESPACE_ID::Metadata WsLoginRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_proto_2fws_2eproto_getter, &descriptor_table_proto_2fws_2eproto_once,
      file_level_metadata_proto_2fws_2eproto[0]);
}

// ===================================================================

class WsLoginResponse::_Internal {
 public:
};

WsLoginResponse::WsLoginResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase(arena, is_message_owned) {
  // @@protoc_insertion_point(arena_constructor:openfoxwq.WsLoginResponse)
}
WsLoginResponse::WsLoginResponse(const WsLoginResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase() {
  WsLoginResponse* const _this = this; (void)_this;
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:openfoxwq.WsLoginResponse)
}





const ::PROTOBUF_NAMESPACE_ID::Message::ClassData WsLoginResponse::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl,
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl,
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*WsLoginResponse::GetClassData() const { return &_class_data_; }







::PROTOBUF_NAMESPACE_ID::Metadata WsLoginResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_proto_2fws_2eproto_getter, &descriptor_table_proto_2fws_2eproto_once,
      file_level_metadata_proto_2fws_2eproto[1]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace openfoxwq
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::openfoxwq::WsLoginRequest*
Arena::CreateMaybeMessage< ::openfoxwq::WsLoginRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::openfoxwq::WsLoginRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::openfoxwq::WsLoginResponse*
Arena::CreateMaybeMessage< ::openfoxwq::WsLoginResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::openfoxwq::WsLoginResponse >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
